name: sspc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  provider: ^5.0.0
  google_fonts: ^3.0.1   # For using the custom fonts
  font_awesome_flutter: ^10.4.0 # For the icons used in the menu
  intl: ^0.19.0
  flutter_secure_storage: ^8.0.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^1.0.0
  shared_preferences: ^2.1.0
  fl_chart: ^0.68.0
  socket_io_client: ^2.0.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  url_launcher: ^6.2.4
  image_picker: ^1.0.4
  image_picker_web: ^3.1.1
  syncfusion_flutter_charts: ^24.2.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/Anas.jpg

